### PR TITLE
Docs update: Remove all references to Blowfish

### PR DESCRIPTION
**Pull request by rohit-710**
## Description

Blowfish is shutting down soon. Consequently, this PR removes all references to Blowfish from the docs. 

## Tests

Tested locally with Docusaurus.

### CODE REVIEW

**Review by joe-reown — CHANGES_REQUESTED** [review]
The removal of Blowfish references looks good however we refer to the domain registry as both "Reown's" and "WalletConnect's" -- so also standardize on referring to is as Reown's?

**Comment by rohit-710** [comment]
> The removal of Blowfish references looks good however we refer to the domain registry as both "Reown's" and "WalletConnect's" -- so also standardize on referring to is as Reown's?

Hey @joe-reown, do you want me to replace "WalletConnect" with "Reown"?

**Comment by joe-reown** [comment]
Yes please!

**Comment by rohit-710** [comment]
> Yes please!

This is done, can you review it again?

**Review by joe-reown — APPROVED** [review]
Looks good!

**Comment by rohit-710** [comment]
> Looks good!

Can you please approve it so I can merge it?

**Review by rtomas — APPROVED** [review]
LGTM

**Pull request merged**
